FROM public.ecr.aws/docker/library/python:3.11.6-slim-bullseye

WORKDIR /backend

COPY ./requirements.txt ./
RUN pip3 install -r requirements.txt --no-cache-dir

COPY ./app ./app

CMD ["app.websocket.handler"]