name: CDK tests
on: push

jobs:
  cdk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: |
          cd cdk
          cd custom-resources/setup-pgvector
          npm ci
          cd ../..
          npm ci
          npm run test
