on:
  push:
    # paths:
    #   - 'backend/**'
    #   - 'frontend/**'
name: Static code analysis
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   issues: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        # TODO: Add these as top-level env vars or use repository/environment secrets
        args: >
          -Dsonar.organization=kylelee24
          -Dsonar.projectKey=kylelee24_bedrock-claude-chat
          -Dsonar.log.level=INFO
          -Dsonar.qualitygate.wait=true
